### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by HeroMines** [NeKitDS/braces.py#2]
I am very new to python, new as in just started, haven't even programmed in it yet. I wanted to give it a try but I find Python's whitespace indentation very dumb and lame, so I want to use this one, however, when I tried to install this for windows it wasn't working for some reason? can you help?
![ice_screenshot_20200427-011509](https://user-images.githubusercontent.com/22183857/80336345-06f35800-8825-11ea-9064-652477e25b78.png)

**Comment by NeKitDS** [comment]
Hey there! Seems like I forgot to include the requirements file in release. Will fix ASAP and release next version! :)

**Comment by NeKitDS** [comment]
For now, you can try to install this library from source:
```sh
python -m pip install -U https://github.com/NeKitDS/braces.py/archive/master.zip
```

**Comment by NeKitDS** [comment]
Okay, this error should be fixed in latest release (`0.1.2`).

```sh
python -m pip install -U braces.py
```

To grab the latest version.

**Comment by HeroMines** [comment]
Alright, thanks, I'll definitely give it a try now and see if it works!

**Comment by HeroMines** [comment]
Fortunately, a lot of the other errors went away. Unfortunately, however, another new error cropped up!
![ice_screenshot_20200427-143730](https://user-images.githubusercontent.com/22183857/80408141-b3b8ee00-8894-11ea-859f-db5105635166.png)

**Comment by NeKitDS** [comment]
Sorry for not replying. Feels like you should install `black` on your own via something like:
```sh
python -m pip install --pre black```

**Comment by HeroMines** [comment]
Alright, I'll give that a try right now.

**Comment by HeroMines** [comment]
There we go! It worked, thanks!
